### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by ssbarnea** [stardust85/repositorytools#1]
Hi,

As I will need to implement an easy to use library for downloading and uploading artifacts it seems that your approach does match very well what I wall looking for.

I would like to join your effort and get this library published to PyPy and to production quality ASAP.

**Comment by stardust85** [comment]
Great! I already created the project on pypi and pypi-test. I have a small problem with versions. We version the code internally, now I have 3.0.52. Can I publish the first version as 3.0.53? :) Feel free to send pull requests, I'll do my best to merge them ASAP.

**Comment by stardust85** [comment]
published on pypi https://pypi.python.org/pypi/repositorytools/

Can I close this issue?

**Comment by stardust85** [comment]
What exactly do you mean by production quality? I was considering to put there 'Stable' to metadata. I was waiting till more people start using it. I use it for few months with no problem.

**Comment by stardust85** [comment]
Uploading works, resolving works, for downloading you can use requests library. Or I can add the download method to NexusRepositoryClient... Can I close it?
