### ISSUE TITLE
lib, cli: upload_artifacts should have an option to use REST API instead of direct POST

### ISSUE THREAD

**Issue by stardust85** [stardust85/repositorytools#16]
Without this, maven metadata don't work and resolving to latest artifact doesn't work.

generate the same traffic as 
`
curl -v -F r=releases -F hasPom=false -F e=jar -F g=com.test -F a=project -F v=1.0 -F p=jar -F file=@project-1.0.jar -u admin:*** http://localhost:8081/nexus/service/local/artifact/maven/content
`
does

**Comment by stardust85** [comment]
http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file

**Comment by oskrkal** [comment]
This should work:
data = {
    'g':local_artifact.group,
    'a':local_artifact.artifact,
    'v':local_artifact.version,
    'p':local_artifact.extension,
    'r':repo_id
}
files = {'file': f}
self._send('service/local/artifact/maven/content', method='POST', data=data, files=files)

**Comment by stardust85** [comment]
The Content-Type header CANNOT be passed as it has to contain also boundary, which is always generated by requests. Spent few hours to find this out
