### ISSUE TITLE
document basic operations: upload, resolve, and delete of artifacts

### ISSUE THREAD

**Issue by ssbarnea** [stardust85/repositorytools#2]
It seems that at this moment the documentation is empty and I do think that it would include at least this:

* how to install, PyPi seems like the best method
* how to download an artefact
* how to upload an aterfact

**Comment by stardust85** [comment]
That's a smart idea. Feel free to send a pull request! :) Please cover it by tests. Please try not to break current API, we already use it at about 10 places.

**Comment by stardust85** [comment]
would you mind if we kept an alternative of reading the variables? Or what about command-line options? We need to run it on a CI server where we don't want to save passwords to disc.

**Comment by ssbarnea** [comment]
Command line options are the worst options as they are extremely visible inside the logs. Environment variables are the way to overwrite configuration ones like .netrc. 

The general rule regarding priority: cmd line argument > environment variable > config file setting

BTW, As you do already use requests library I think you already benefit from the .netrc feature. I need to double check but as far as I know they do use the information from it when the file exists.

**Comment by stardust85** [comment]
I agree that command-line options for credentials are bad idea, it was just an idea ;). I propose to keep env. variables and to add  .netrc, which will have lower priority than env. variables - as you proposed.

**Comment by stardust85** [comment]
regarding the downloads, they aren't present there yet. Feel free to implement them. Regarding the documentation, I agree it is insufficient. I'll try to immprove it, but I can't guarantee any deadline.

**Comment by stardust85** [comment]
I implemented a resolve api method and cli artifact's subcommand, you can use it in download(...) method in your pull request

**Comment by stardust85** [comment]
I added some examples to readme.rst, docs on rtfd currently broken

**Comment by stardust85** [comment]
you can support my effort via gratipay ;)

**Comment by stardust85** [comment]
for downloading I created a special issue https://github.com/stardust85/repositorytools/issues/4
