### ISSUE TITLE
Wrong number of arguments potentially passed to CLI.run method

### ISSUE THREAD

**Issue by oskrkal** [stardust85/repositorytools#24]
There is a bug in ``repositorytools.cli.common`` module in passing arguments to ``CLI.run`` method in ``CLI.__call__``. The ``run`` method takes only one argument, which is expected to be a list, but the ``__call__`` method passes in expanded variable list of arguments, which can result in wrong argument number error.

```
class CLI(collections.Callable):
    def run(self, args=None):
        pass  # some stuff done here

    def __call__(self, *args):
        self.run(*args)    # line 58; should be self.run(args)
        return 0
```

The above code can result, for example, in `TypeError: run() takes at most 2 arguments (3 given)` error with the following code:

```
class MyCLI(CLI):
    def _get_parser(self):
        return argparse.ArgumentParser()

MyCLI()("arg1", "arg2")
```

**Comment by stardust85** [comment]
this is a root cause of #29
