### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by Lucas-C** [stardust85/repositorytools#29]
Bug reproduction:
```
artifact --help
```

**Comment by Lucas-C** [comment]
Under Python 3.4.3 with Cygwin and:
```
repositorytools==4.2.2
````

**Comment by stardust85** [comment]
Hi, I was able to reproduce the error in my cygwin in a venv. Now I'll verify that your version fixes the problem and if so, I'll merge it

**Comment by stardust85** [comment]
Closed by PR #30

**Comment by stardust85** [comment]
Released in 4.2.3
