### ISSUE TITLE
recommand by sonatype official site

### ISSUE THREAD

**Issue by hanbeibei** [stardust85/repositorytools#7]
congratulation!

the link is:
https://books.sonatype.com/nexus-book/reference/_nexus_integrations.html

the other related repo build in ruby:
https://github.com/RiotGamesMinions/nexus_cli

which is used by nexus cookbook:
https://github.com/RiotGamesCookbooks/nexus-cookbook

I suppose there are some works need to be done, especially for paper work( more detail document)

Best regards
Oliver

**Comment by hanbeibei** [comment]
I'm reading the src code, I'm not sure using repositorytools upload jar file, could we get the jar's dependency?

**Comment by stardust85** [comment]
Hi, I'm not a java/maven expert, but according to https://maven.apache.org/pom.html#Dependencies, to describe jar's dependencies, you should upload a pom file, which describes them. Then maven should be able to download them.

uploading a jar and pom:
export REPOSITORY_URL=http://repo.example.com
export REPOSITORY_USER=admin
export REPOSITORY_PASSWORD=mysecretpassword

artifact upload foo-1.2.3.jar releases com.fooware
artifact upload foo-1.2.3.pom releases com.fooware

BTW if you work with jars and POMs, maybe maven or gradle will work for you better.

**Comment by stardust85** [comment]
Can I close this issue?

**Comment by hanbeibei** [comment]
yes, of course!, it seems this can not resolve Jar dependency, that's ok, never mind
