### ISSUE TITLE
try to download artifact.

### ISSUE THREAD

**Issue by hanbeibei** [stardust85/repositorytools#8]
Hello, 

I upload a foo-bar-1.0.jar file to my local machine repo, and write these script:

import repositorytools
from repositorytools.lib.artifact import Artifact, RemoteArtifact

url = 'http://localhost:8081/nexus/content/repositories/releases'

client = repositorytools.NexusRepositoryClient(repository_url=url, user='admin',password='admin123')

artifact = RemoteArtifact.from_repo_id_and_coordinates('Release', 'foo:bar:1.0:demo:jar')
print(artifact)
client.resolve_artifact(artifact)
print(client)

got the result of this statement: 

>>print(artifact)

foo:bar:1.0:demo:jar

it seems not right, and the later statement 

>>client.resolve_artifact(artifact)

report _send_json function failed.

it seems that the file in lib/artifact.py RemoteArtifact.from_repo_id_and_coordinates() can not resolve a json format . I change my code:

artifact = RemoteArtifact.from_repo_id_and_coordinates('Release', 'foo:bar:1.0')

but get the result:

foo:bar:1.0::

and still failed, 

I'm not sure the root cause, i'm not quite familiar with requests module, Could you post some demo code about upload,  download and delete?

**Comment by hanbeibei** [comment]
oh.. what a markdown format..

**Comment by stardust85** [comment]
> report _send_json function failed.
Please send a traceback if there is any

**Comment by hanbeibei** [comment]
foo:bar:1.0:demo:jar
Traceback (most recent call last):
  File "nexus.py", line 44, in <module>
    client.resolve_artifact(artifact)
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\li
\repository.py", line 87, in resolve_artifact
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\li
\repository.py", line 186, in _send_json
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\li
\repository.py", line 176, in _send
  File "C:\Anaconda3\lib\site-packages\requests\models.py", line 808, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

**Comment by stardust85** [comment]
Instead of
```
url = 'http://localhost:8081/nexus/content/repositories/releases'
```
try
```
url =  'http://localhost:8081/nexus/'
```
and instead of
```
artifact = RemoteArtifact.from_repo_id_and_coordinates('Release', 'foo:bar:1.0:demo:jar')
```
try
```
artifact = RemoteArtifact.from_repo_id_and_coordinates('releases', 'foo:bar:1.0:demo:jar')
```

**Comment by stardust85** [comment]
Can I close it?

**Comment by hanbeibei** [comment]
oh.. Please hold on, I'm get home now, I will updated it tomorrow..

Great appreciate for your help!

**Comment by stardust85** [comment]
Ok, no problem. Feel free to support my effort via donations on Gratipay https://gratipay.com/~stardust85

**Comment by hanbeibei** [comment]
Hello:

I try to update the code, current code is: 

import repositorytools
from repositorytools.lib.artifact import Artifact, RemoteArtifact

url = 'http://localhost:8081/nexus/'

client = repositorytools.NexusRepositoryClient(repository_url=url, user='admin',password='admin123')

artifact = RemoteArtifact.from_repo_id_and_coordinates('releases', 'foo:bar:1.0:demo:jar')
print(artifact)
client = repositorytools.repository_client_factory()
client.resolve_artifact(artifact)
print(client)

still get the eror message:

foo:bar:1.0:demo:jar
Traceback (most recent call last):
  File "nexus.py", line 92, in <module>
    client.resolve_artifact(artifact)
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\lib
\repository.py", line 87, in resolve_artifact
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\lib
\repository.py", line 186, in _send_json
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\lib
\repository.py", line 176, in _send
  File "C:\Anaconda3\lib\site-packages\requests\models.py", line 808, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

I notice the delete function is almost the same as download, so I try the upload,  in these code:

import repositorytools
from repositorytools.lib.artifact import Artifact, RemoteArtifact

url = 'http://localhost:8081/nexus/'

artifact = repositorytools.LocalArtifact(local_path='c:\\work\\oliver-1.2.3.jar', group='foo')
print(artifact)

client = repositorytools.repository_client_factory(repository_url=url,user='admin',password='admin123')

remote_artifacts = client.upload_artifacts(local_artifacts=[artifact], repo_id='releases')
print(remote_artifacts)

but get the error message like this:

foo:oliver:1.2.3::
Traceback (most recent call last):
  File "nexus.py", line 53, in <module>
    remote_artifacts = client.upload_artifacts(local_artifacts=[artifact], repo_id='releas
es')
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\lib
\repository.py", line 108, in upload_artifacts
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\lib
\repository.py", line 131, in _upload_artifact
  File "C:\Anaconda3\lib\site-packages\repositorytools-4.0.2-py3.4.egg\repositorytools\lib
\repository.py", line 176, in _send
  File "C:\Anaconda3\lib\site-packages\requests\models.py", line 808, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed

it seems that the info which passed to is correct:
artifact = RemoteArtifact.from_repo_id_and_coordinates('releases', 'foo:bar:1.0:demo:jar')
print(artifact.repo_id)

I can get output: release and the other is correct, 

it seems that is the request(i'm not sure), Could you please help me on this?

sorry for bringing inconvience.

Best regards
Oliver

**Comment by hanbeibei** [comment]
In repository.py, resolve_artifact method, the string 'service/local/artifact/maven/resolve' is treated as path, i'm not sure it is valid..??

**Comment by stardust85** [comment]
Probably your artifact is missing:

https://oss.sonatype.org/service/local/artifact/maven/resolve?g=org.codehaus.jtstand&a=jtstand-core&v=0.98&r=codehaus-releases (should show some xml or if you path accept:application/json than json)
https://oss.sonatype.org/service/local/artifact/maven/resolve?g=org.codehaus.jtstand&a=idontexist&v=0.98&r=codehaus-releases (should show 404)

Try debug mode (artifact -D resolve ...)

**Comment by stardust85** [comment]
You can also try running system tests or compare the code in system tests with your code. Unfortunately it is not running on travis CI yet...

**Comment by hanbeibei** [comment]
oh..Ok, I don't know hot to run it on command line, never mind, I will try it on..

**Comment by stardust85** [comment]
You can run tests conveniently in vagrant as documented in https://github.com/stardust85/repositorytools/blob/master/docs/development.rst

**Comment by hanbeibei** [comment]
oh..Ok, I get it,

I'm trying it on my private Nexus repo, the function which I wanted is quite simple, download , delete and upload via python code, I try to upload a jar file manually, now, I can notice it on browser and download it via this link:

http://localhost:8081/nexus/content/repositories/releases/foo/bar/1.0/bar-1.0-demo.jar, 

I can download it via browser directly in python, but I have no idea how to upload and delete, so I choose to search related module of python on internet.

**Comment by stardust85** [comment]
You can use the http methods PUT and DELETE. Don't forget authentication.

**Comment by hanbeibei** [comment]
wow... thanks!!

how dizzy I am..

**Comment by hanbeibei** [comment]
It's done, Please close this issue, Great appreciate
